import { db } from './src/db/db.js';
import { users, quests, items, userInventories } from './src/db/schema.js';

async function seed() {
  try {
    console.log("🚀 Starting database seeding with Drizzle...");

    // 1. Clean out existing data (Order matters due to Foreign Key links)
    await db.delete(userInventories);
    await db.delete(items);
    await db.delete(quests);
    await db.delete(users);
    console.log("🧹 Cleaned out existing table rows.");

    // 2. Insert mock user and catch the returned user row to get their ID
    const [insertedUser] = await db.insert(users).values({
      name: 'Rin',
      title: 'the Wayfinder',
      level: 7,
      xp: 4820,
      energy: 68,
      coins: 1284,
      bossHp: 640
    }).returning(); // .returning() gets the exact row data generated by the DB

    console.log(`👤 Seeded user: ${insertedUser.name} (ID: ${insertedUser.id})`);

    // 3. Insert mock quests using mass insert batching
    const mockQuests = [
      { id: "q1", title: "Complete deep-work sprint", category: "Focus", stat: "Intelligence", duration: "90m", difficulty: "Hard", rarity: "Legendary", xp: 120 },
      { id: "q2", title: "Morning meditation", category: "Mindfulness", stat: "Wisdom", duration: "15m", difficulty: "Easy", rarity: "Common", xp: 30 },
      { id: "q3", title: "Review pull requests", category: "Work", stat: "Intelligence", duration: "45m", difficulty: "Medium", rarity: "Rare", xp: 60 },
      { id: "q4", title: "Go for a run", category: "Fitness", stat: "Strength", duration: "30m", difficulty: "Medium", rarity: "Uncommon", xp: 50 },
    ];
    await db.insert(quests).values(mockQuests);
    console.log(`⚔️  Seeded ${mockQuests.length} quests.`);

    // 4. Insert mock items (ores and equipment) into the database
    const mockItems = [
      { id: 'ore_iron', name: 'Iron Ore', itemType: 'Material', rarity: 'Common', icon: '🪨', sellPrice: 10 },
      { id: 'ore_gold', name: 'Gold Ore', itemType: 'Material', rarity: 'Rare', icon: '🪙', sellPrice: 50 },
      { id: 'ore_diamond', name: 'Diamond Ore', itemType: 'Material', rarity: 'Legendary', icon: '💎', sellPrice: 200 },
      { id: 'eq1', name: 'Iron Plate', itemType: 'Armor', rarity: 'Uncommon', icon: '🛡️', stats: '+10 DEF', sellPrice: 100 },
      { id: 'eq2', name: 'Crystal Guard', itemType: 'Armor', rarity: 'Rare', icon: '🛡️', stats: '+25 DEF', sellPrice: 300 },
      { id: 'eq3', name: 'Shadow Cloak', itemType: 'Armor', rarity: 'Epic', icon: '🧥', stats: '+40 DEF, +5 AGI', sellPrice: 800 },
      { id: 'eq4', name: 'Ring of Focus', itemType: 'Accessory', rarity: 'Uncommon', icon: '💍', stats: '+5 INT', sellPrice: 150 },
      { id: 'eq5', name: 'Amulet of Time', itemType: 'Accessory', rarity: 'Rare', icon: '📿', stats: '+10 WIS', sellPrice: 400 },
      { id: 'eq6', name: 'Wayfinder Charm', itemType: 'Accessory', rarity: 'Legendary', icon: '✨', stats: '+20 ALL', sellPrice: 2000 },
    ];
    await db.insert(items).values(mockItems);
    console.log(`💎 Seeded master item list.`);

    // 5. Connect item instances to Rin's inventory
    await db.insert(userInventories).values([
      { userId: insertedUser.id, itemId: 'ore_iron', quantity: 5 },
      { userId: insertedUser.id, itemId: 'ore_diamond', quantity: 1 },
      { userId: insertedUser.id, itemId: 'eq1', quantity: 1 },
      { userId: insertedUser.id, itemId: 'eq4', quantity: 1 },
      { userId: insertedUser.id, itemId: 'eq6', quantity: 1 },
    ]);
    console.log(`🎒 Populated user inventory.`);

    console.log("✨ Database seeded perfectly with Drizzle ORM!");
  } catch (error) {
    console.error("❌ Error seeding database:", error);
  } finally {
    // Process exits naturally here or you can invoke process.exit(0);
    process.exit(0);
  }
}


seed();
